{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: stranger-map-operator
    namespace: stranger-map
    labels:
      control-plane: stranger-map-operator
      app.kubernetes.io/version: "2.4.0"