stages:
  - build
  - test
  - dist
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/backend/.gradle"
  - export GRADLE_USER_HOME

build_backend:
  stage: build
  image: gradle:jdk17-alpine
  script:
    - cd backend/
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test_backend:
  stage: test
  image: gradle:jdk17-alpine
  script:
    - cd backend/
    - gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

build_backend_dockerfile:
  stage: dist
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  dependencies:
    - build_backend
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
