name: Build Java Maven project
 
on: [push, pull_request]
 
jobs:
  compile:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}
      - name: Compile the Project
        working-directory: backend
        run: mvn -B compile
 
  buildbackendjava:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build the Maven Project
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
    - name: Build and test project
      working-directory: backend
      run: mvn -B verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: stranger-map-backend.jar
        path: backend/target/stranger-map-backend-1.0.0.jar

  buidbackenddocker:
    runs-on: ubuntu-20.04
    needs: buildbackendjava
    name: Build Docker Container
    steps:
    - uses: actions/checkout@v2
    - name: Download Maven build artifact
      uses: actions/download-artifact@v2
      with:
        name: stranger-map-backend.jar
        path: backend/target
    - name: Build Docker container
      working-directory: backend
      run: |
        docker build -t szsascha/stranger-map-backend .
#        docker save --output stranger-map-backend.dockerimage.tar szsascha/stranger-map-backend:latest
#    - name: Upload docker image
#      uses: actions/upload-artifact@v2
#      with:
#        name: stranger-map-backend.dockerimage.tar
#        path: backend/stranger-map-backend.dockerimage.tar